const carSeeds = [
    {
      brandId: 1,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 2,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 3,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 4,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 5,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 6,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 7,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 8,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
    {
      brandId: 9,
      model: "Civic",
      year: 2010,
      typeId: 1,
      pricePerMinute: 0.2,
      engineCapacity: 1.8,
    },
  ];