const carsSeed = [
  {
    brandId: 1,
    model: "Avensis",
    year: 2010,
    registration: "AA-1234",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 1.6,
    pricePerMinute: 0.1,
    typeId: 1,
  },
  {
    brandId: 5,
    model: "Mustang",
    year: 2018,
    registration: "CC-9012",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 2.3,
    pricePerMinute: 0.15,
    typeId: 3,
  },
  {
    brandId: 1,
    model: "Corolla",
    year: 2019,
    registration: "DD-3456",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 1.6,
    pricePerMinute: 0.11,
    typeId: 1,
  },
  {
    brandId: 3,
    model: "X5",
    year: 2020,
    registration: "EE-7890",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 2.0,
    pricePerMinute: 0.18,
    typeId: 2,
  },
  {
    brandId: 8,
    model: "Polo",
    year: 2016,
    registration: "FF-2468",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 1.4,
    pricePerMinute: 0.09,
    typeId: 1,
  },
  {
    brandId: 2,
    model: "Accord",
    year: 2017,
    registration: "GG-1357",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 2.0,
    pricePerMinute: 0.13,
    typeId: 3,
  },
  {
    brandId: 8,
    model: "Fiesta",
    year: 2014,
    registration: "HH-3691",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 1.5,
    pricePerMinute: 0.1,
    typeId: 2,
  },
  {
    brandId: 1,
    model: "Camry",
    year: 2021,
    registration: "II-8023",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 2.5,
    pricePerMinute: 0.16,
    typeId: 3,
  },
  {
    brandId: 11,
    model: "Q5",
    year: 2019,
    registration: "JJ-4567",
    available: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    engineCapacity: 2.0,
    pricePerMinute: 0.14,
    typeId: 1,
  },
];

export { carsSeed };
